// Compiles the Nuxt site's CSS for the WordPress plugin.
//
//   node wordpress/tools/compile-css.mjs
//
// base.css is app/assets/css/main.css with its font path rewritten.
//
// components.css is every <style scoped> block, run through Vue's own compiler
// so :deep(), :global(), pseudo-elements and keyframes are handled exactly as
// Nuxt handles them. Vue marks a scoped rule with an attribute every element
// of the component carries, [data-v-x]; here the component's root carries a
// class instead, and the attribute becomes :is(.x, .x *). That has the same
// specificity as the attribute, so every rule wins or loses exactly where it
// does on the Nuxt site.
//
// It must also match the same elements. Vue gives the attribute to the
// component's own elements and to the root of a child component, never to
// what is inside a child, nor to the roots of a child with several roots (a
// fragment, like PhotoNote). So a rule is fenced off from the inside of the
// child components its template uses, and from fragment roots, with :where()
// so the fence adds no specificity:
//   :is(.x,.x *):not(:where(.child-a,.child-b) *):not(:where(.fragment))
// Without it, HomeOpen's `.hero` would reach PhotoNote's `.pn.hero`.

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { dirname, resolve, relative, basename } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse, compileStyle } from '@vue/compiler-sfc'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const app = resolve(root, 'app')
const dest = resolve(root, 'wordpress/dilytics-modules/assets/css')

// shared pieces first, then the sections, then the pages, as Nuxt loads them
const ORDER = ['components', 'components/home', 'pages']

const kebab = (s) =>
  s.replace(/[[\]]/g, '').replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase()

export const scopeOf = (file) => 'v-' + kebab(basename(file, '.vue'))

function vueFiles(dir) {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.vue') && statSync(resolve(dir, f)).isFile())
    .sort()
    .map((f) => resolve(dir, f))
}

// Every component: its scope (when it has scoped styles), the components its
// template uses, and whether it renders several roots.
const info = new Map()
for (const sub of ORDER) {
  for (const file of vueFiles(resolve(app, sub))) {
    const { descriptor } = parse(readFileSync(file, 'utf8'), { filename: file })
    const tags = new Set()
    const walk = (n) => {
      if (n.type === 1 && /^[A-Z]/.test(n.tag)) tags.add(n.tag)
      for (const c of n.children || []) walk(c)
    }
    const ast = descriptor.template?.ast
    if (ast) walk(ast)
    const roots = (ast?.children || []).filter((n) => n.type === 1)
    info.set(basename(file, '.vue'), {
      file,
      descriptor,
      scope: descriptor.styles.length ? scopeOf(file) : null,
      tags,
      fragment: roots.length > 1 || (roots.length === 1 && roots[0].tag === 'template'),
    })
  }
}

let css = ''
const seen = new Map()
for (const [, c] of info) {
  const { file, descriptor, scope } = c
  if (!scope) continue
  if (seen.has(scope)) throw new Error(`scope ${scope} used by ${seen.get(scope)} and ${file}`)
  seen.set(scope, file)

  const kids = [...c.tags].map((t) => info.get(t)).filter((k) => k && k.scope && k.scope !== scope)
  let mark = `:is(.${scope},.${scope} *)`
  if (kids.length) mark += `:not(:where(${kids.map((k) => '.' + k.scope).join(',')}) *)`
  const frags = kids.filter((k) => k.fragment)
  if (frags.length) mark += `:not(:where(${frags.map((k) => '.' + k.scope).join(',')}))`

  for (const b of descriptor.styles) {
    if (!b.scoped) throw new Error(`${file}: unscoped style block`)
    const r = compileStyle({ source: b.content, filename: file, id: `data-v-${scope}`, scoped: true })
    if (r.errors.length) throw r.errors[0]
    const out = r.code.replaceAll(`[data-v-${scope}]`, mark)
    if (out.includes('[data-v-')) throw new Error(`${file}: unconverted scope attribute`)
    css += `\n/* ${relative(app, file)} → .${scope} */\n${out.trim()}\n`
  }
}

const head = '/* Generated by wordpress/tools/compile-css.mjs from the Nuxt components. Do not edit. */\n'
writeFileSync(resolve(dest, 'components.css'), head + css)

const main = readFileSync(resolve(app, 'assets/css/main.css'), 'utf8').replace(
  "url('~/assets/fonts/archivo.woff2')",
  "url('../fonts/archivo.woff2')",
)
if (!main.includes('../fonts/archivo.woff2')) throw new Error('font path not rewritten')
writeFileSync(resolve(dest, 'base.css'), head + main)

// Every class name the Nuxt CSS styles. WordPress puts classes of its own on
// <body> (page, home…); the plugin strips any that the Nuxt CSS would style,
// since the Nuxt <body> has none: `.page` alone would narrow the whole site.
const classes = new Set()
for (const m of (main + css).replace(/\/\*[\s\S]*?\*\//g, '').matchAll(/\.(-?[_a-zA-Z][\w-]*)/g)) {
  if (!/^\d/.test(m[1])) classes.add(m[1])
}
writeFileSync(resolve(dest, 'classes.json'), JSON.stringify([...classes].sort()))

console.log([...seen.keys()].join(' '))
